/*******************************************************************************
 * Copyright 2014 The MITRE Corporation
 *   and the MIT Kerberos and Internet Trust Consortium
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.mitre.uma.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import java.util.Set;

import org.springframework.security.oauth2.provider.OAuth2Authentication;
import javax.persistence.ElementCollection;
import javax.persistence.CollectionTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Entity class for resource sets
 * 
 * @author tsitkov
 *
 */
@Entity
@Table(name = "resource_set")
@NamedQueries({
	@NamedQuery(name = "ResourceSetEntityUma.getBySetId", query = "select a from ResourceSetEntityUma a where a.setId = :set_id"),
	@NamedQuery(name = "ResourceSetEntityUma.getByRsId", query = "select a from ResourceSetEntityUma a where a.rsId = :rsId"),
	@NamedQuery(name = "ResourceSetEntityUma.getBySetIdAndRev", query = "select a from ResourceSetEntityUma a where a.setId = :set_id and a.revision = :revision"),
	@NamedQuery(name = "ResourceSetEntityUma.getBySetIdAndScope", query = "select a from ResourceSetEntityUma a where (a.setId = :set_id) and (a.scope = :scope)")
})
public class ResourceSetEntityUma {

	private Long id;
	private String rsId; /* resource set id passed by RS */
	private String rs_owner_id;
	private String rs_owner_name;
	private String pat;
	private String server_id;
	private String name;
	private String set_id; /* resource set id created by AS */
	private Set<String> scope;
	private String revision; /* Same as  Etag */

	/**
	 * Default constructor.
	 */
	public ResourceSetEntityUma() {

	}

	/**
	 * Create a new ResourceSetEntityUma with the given pat, server_id, etc.
	 * 
	 * @param rsId	 	Resource set id passed from RS
	 * @param pat		PAT token
	 * @param server_id 	Resource server id 
	 * @param set_id 	Resource set id
	 * @param scope 	Resource scope
	 * @param revision 	Resource set registered revision
	 * @param name	 	Resource set name
	 * @param set_id 	Resource set id generated by AS
	 * @param rs_owner_id 	Resource owner's id
	 * @param rs_owner_name	Resource owner's name
	 */
	public ResourceSetEntityUma( String pat, String server_id, String rs_owner_id, String rs_owner_name,  
				     String name,  String set_id, Set<String> scope, String revision ) {

		this.rsId = rsId; 
		this.pat = pat;
		this.server_id = server_id;
		this.rs_owner_id = rs_owner_id;
		this.rs_owner_name = rs_owner_name;
		this.name = name;
		this.set_id = set_id;
		this.name = name;
		this.revision = revision;
	}

	/**
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}


	/**
	 * @return the rsId
	 */
	@Basic
	@Column(name = "rsid")
	public String getRsId() {
		return rsId;
	}

	/**
	 * @param rsId  the rsId to set
	 */
	public void setRsId(String rsId) {
		this.rsId = rsId;
	}

	/**
	/**
	 * @return the UMA PAT
	 */
	@Basic
	@Column(name = "pat")
	public String getPat() {
		return pat;
	}

	/**
	 * @param pat  the pat to set
	 */
	public void setPat(String pat) {
		this.pat = pat;
	}

	/**
	 * @return the server_id
	 */
	@Basic
	@Column(name = "server_id")
	public String getServerId() {
		return server_id;
	}

	/**
	 * @param server_id  the ID of the RS that controls this resource set
	 */
	public void setServerId(String server_id) {
		this.server_id = server_id;
	}

	/**
	 * @return the name of the resource set
	 */
	@Basic
	@Column(name = "name")
	public String getName() {
		return name;
	}

	/**
	 * @param name  the resource set name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the Resource Set ID
	 */
	@Basic
	@Column(name = "set_id")
	public String getSetId() {
		return set_id;
	}

	/**
	 * @param set_id  the Resource Set ID to set
	 */
	public void setSetId(String set_id) {
		this.set_id = set_id;
	}

	/**
	 * @return the Resource Set registered scopes
	 */
        @ElementCollection(fetch = FetchType.EAGER)
        @CollectionTable(
                        name="resource_set_registered_scope",
                        joinColumns=@JoinColumn(name="set_id")
                        )
        @Basic
        @Column(name = "scope")
	public Set<String> getScope() {
		return scope;
	}

	/**
	 * @param scope  the Resource Set scope to set
	 */
	public void setScope(Set<String> scope) {
		this.scope = scope;
	}

	/**
	 * @return the Resource Set revision
	 */
	@Basic
	@Column(name = "revision")
	public String getRevision() {
		return revision;
	}

	/**
	 * @param revision  the Resource Set revision to set
	 */
	public void setRevision(String revision) {
		this.revision = revision;
	}

	/**
	 * @return the resource owner's id
	 */

	@Basic
	@Column(name = "rs_owner_id")
	public String getOwnerId() {
		return rs_owner_id;
	}

	/**
	 * @param rs_owner_id  the owner id to set
	 */

	public void setOwnerId(String rs_owner_id) {
		this.rs_owner_id = rs_owner_id;
	}

	/**
	 * @return the resourse owner's name
	 */

	@Basic
	@Column(name = "rs_owner_name")
	public String getOwnerName() {
		return rs_owner_name;
	}

	/**
	 * @param rs_owner_name  the resource owner's name to set
	 */
	public void setOwnerName(String rs_owner_name) {
		this.rs_owner_name = rs_owner_name;
	}

}
